import json

items = [
    # Building Blocks (Extended)
    {"id": "minecraft:cobblestone", "price": 5, "category": "Building"},
    {"id": "minecraft:stone", "price": 10, "category": "Building"},
    {"id": "minecraft:stone_bricks", "price": 12, "category": "Building"},
    {"id": "minecraft:mossy_cobblestone", "price": 15, "category": "Building"},
    {"id": "minecraft:mossy_stone_bricks", "price": 18, "category": "Building"},
    {"id": "minecraft:cracked_stone_bricks", "price": 15, "category": "Building"},
    {"id": "minecraft:dirt", "price": 2, "category": "Building"},
    {"id": "minecraft:grass_block", "price": 20, "category": "Building"},
    {"id": "minecraft:sand", "price": 5, "category": "Building"},
    {"id": "minecraft:red_sand", "price": 8, "category": "Building"},
    {"id": "minecraft:gravel", "price": 5, "category": "Building"},
    {"id": "minecraft:glass", "price": 15, "category": "Building"},
    {"id": "minecraft:oak_log", "price": 20, "category": "Building"},
    {"id": "minecraft:spruce_log", "price": 20, "category": "Building"},
    {"id": "minecraft:birch_log", "price": 20, "category": "Building"},
    {"id": "minecraft:jungle_log", "price": 20, "category": "Building"},
    {"id": "minecraft:acacia_log", "price": 20, "category": "Building"},
    {"id": "minecraft:dark_oak_log", "price": 20, "category": "Building"},
    {"id": "minecraft:mangrove_log", "price": 20, "category": "Building"},
    {"id": "minecraft:cherry_log", "price": 20, "category": "Building"},
    {"id": "minecraft:oak_planks", "price": 5, "category": "Building"},
    {"id": "minecraft:deepslate", "price": 15, "category": "Building"},
    {"id": "minecraft:polished_deepslate", "price": 18, "category": "Building"},
    {"id": "minecraft:deepslate_bricks", "price": 20, "category": "Building"},
    {"id": "minecraft:white_wool", "price": 30, "category": "Building"},
    {"id": "minecraft:granite", "price": 8, "category": "Building"},
    {"id": "minecraft:polished_granite", "price": 12, "category": "Building"},
    {"id": "minecraft:diorite", "price": 8, "category": "Building"},
    {"id": "minecraft:polished_diorite", "price": 12, "category": "Building"},
    {"id": "minecraft:andesite", "price": 8, "category": "Building"},
    {"id": "minecraft:polished_andesite", "price": 12, "category": "Building"},
    {"id": "minecraft:sandstone", "price": 10, "category": "Building"},
    {"id": "minecraft:red_sandstone", "price": 12, "category": "Building"},
    {"id": "minecraft:quartz_block", "price": 160, "category": "Building"},
    {"id": "minecraft:smooth_quartz", "price": 180, "category": "Building"},
    {"id": "minecraft:white_concrete", "price": 25, "category": "Building"},
    {"id": "minecraft:black_concrete", "price": 25, "category": "Building"},
    {"id": "minecraft:white_terracotta", "price": 20, "category": "Building"},
    {"id": "minecraft:sea_lantern", "price": 400, "category": "Building"},
    {"id": "minecraft:glowstone", "price": 150, "category": "Building"},

    # Materials
    {"id": "minecraft:iron_ingot", "price": 100, "category": "Materials"},
    {"id": "minecraft:raw_iron", "price": 80, "category": "Materials"},
    {"id": "minecraft:copper_ingot", "price": 50, "category": "Materials"},
    {"id": "minecraft:gold_ingot", "price": 400, "category": "Materials"},
    {"id": "minecraft:diamond", "price": 2000, "category": "Materials"},
    {"id": "minecraft:emerald", "price": 500, "category": "Materials"},
    {"id": "minecraft:netherite_ingot", "price": 15000, "category": "Materials"},
    {"id": "minecraft:coal", "price": 20, "category": "Materials"},
    {"id": "minecraft:charcoal", "price": 15, "category": "Materials"},
    {"id": "minecraft:quartz", "price": 40, "category": "Materials"},
    {"id": "minecraft:amethyst_shard", "price": 100, "category": "Materials"},
    {"id": "minecraft:lapis_lazuli", "price": 150, "category": "Materials"},
    {"id": "minecraft:redstone", "price": 30, "category": "Materials"},

    # Food
    {"id": "minecraft:apple", "price": 20, "category": "Food"},
    {"id": "minecraft:bread", "price": 30, "category": "Food"},
    {"id": "minecraft:cooked_beef", "price": 60, "category": "Food"},
    {"id": "minecraft:cooked_porkchop", "price": 60, "category": "Food"},
    {"id": "minecraft:cooked_chicken", "price": 50, "category": "Food"},
    {"id": "minecraft:cooked_salmon", "price": 50, "category": "Food"},
    {"id": "minecraft:cooked_cod", "price": 45, "category": "Food"},
    {"id": "minecraft:golden_apple", "price": 2000, "category": "Food"},
    {"id": "minecraft:golden_carrot", "price": 150, "category": "Food"},
    {"id": "minecraft:enchanted_golden_apple", "price": 50000, "category": "Food"},
    {"id": "minecraft:potato", "price": 10, "category": "Food"},
    {"id": "minecraft:carrot", "price": 10, "category": "Food"},
    {"id": "minecraft:melon_slice", "price": 5, "category": "Food"},
    {"id": "minecraft:pumpkin_pie", "price": 40, "category": "Food"},

    # Mob Drops
    {"id": "minecraft:rotten_flesh", "price": 10, "category": "Mob Drops"},
    {"id": "minecraft:bone", "price": 20, "category": "Mob Drops"},
    {"id": "minecraft:gunpowder", "price": 80, "category": "Mob Drops"},
    {"id": "minecraft:string", "price": 15, "category": "Mob Drops"},
    {"id": "minecraft:spider_eye", "price": 50, "category": "Mob Drops"},
    {"id": "minecraft:ender_pearl", "price": 250, "category": "Mob Drops"},
    {"id": "minecraft:blaze_rod", "price": 400, "category": "Mob Drops"},
    {"id": "minecraft:ghast_tear", "price": 1500, "category": "Mob Drops"},
    {"id": "minecraft:slime_ball", "price": 300, "category": "Mob Drops"},
    {"id": "minecraft:leather", "price": 40, "category": "Mob Drops"},
    {"id": "minecraft:feather", "price": 10, "category": "Mob Drops"},
    {"id": "minecraft:magma_cream", "price": 350, "category": "Mob Drops"},
    {"id": "minecraft:phantom_membrane", "price": 800, "category": "Mob Drops"},

    # Utility (Survival Tools)
    {"id": "minecraft:torch", "price": 5, "category": "Utility"},
    {"id": "minecraft:soul_torch", "price": 10, "category": "Utility"},
    {"id": "minecraft:lantern", "price": 120, "category": "Utility"},
    {"id": "minecraft:crafting_table", "price": 20, "category": "Utility"},
    {"id": "minecraft:furnace", "price": 30, "category": "Utility"},
    {"id": "minecraft:chest", "price": 40, "category": "Utility"},
    {"id": "minecraft:barrel", "price": 40, "category": "Utility"},
    {"id": "minecraft:white_bed", "price": 150, "category": "Utility"},
    {"id": "minecraft:iron_pickaxe", "price": 350, "category": "Utility"},
    {"id": "minecraft:iron_axe", "price": 350, "category": "Utility"},
    {"id": "minecraft:iron_sword", "price": 250, "category": "Utility"},
    {"id": "minecraft:iron_shovel", "price": 150, "category": "Utility"},
    {"id": "minecraft:diamond_pickaxe", "price": 6500, "category": "Utility"},
    {"id": "minecraft:diamond_axe", "price": 6500, "category": "Utility"},
    {"id": "minecraft:diamond_sword", "price": 4500, "category": "Utility"},
    {"id": "minecraft:water_bucket", "price": 350, "category": "Utility"},
    {"id": "minecraft:lava_bucket", "price": 500, "category": "Utility"},
    {"id": "minecraft:shield", "price": 500, "category": "Utility"},
    {"id": "minecraft:ender_chest", "price": 10000, "category": "Utility"},
    {"id": "minecraft:shulker_box", "price": 20000, "category": "Utility"},
    {"id": "minecraft:totem_of_undying", "price": 25000, "category": "Utility"},
    {"id": "minecraft:campfire", "price": 50, "category": "Utility"},
    {"id": "minecraft:shears", "price": 250, "category": "Utility"},

    # Nature
    {"id": "minecraft:oak_sapling", "price": 40, "category": "Nature"},
    {"id": "minecraft:spruce_sapling", "price": 40, "category": "Nature"},
    {"id": "minecraft:birch_sapling", "price": 40, "category": "Nature"},
    {"id": "minecraft:sugar_cane", "price": 15, "category": "Nature"},
    {"id": "minecraft:wheat_seeds", "price": 5, "category": "Nature"},
    {"id": "minecraft:pumpkin_seeds", "price": 20, "category": "Nature"},
    {"id": "minecraft:melon_seeds", "price": 20, "category": "Nature"},
    {"id": "minecraft:bamboo", "price": 10, "category": "Nature"},
    {"id": "minecraft:pink_petals", "price": 50, "category": "Nature"},
    {"id": "minecraft:oak_leaves", "price": 5, "category": "Nature"},
    {"id": "minecraft:lily_pad", "price": 80, "category": "Nature"},
]

entries = []
for item in items:
    entries.append({
        "registryId": item["id"],
        "count": 1,
        "price": item["price"],
        "stock": 0,
        "buyEnabled": True,
        "sellEnabled": True,
        "category": item["category"]
    })

print(json.dumps(entries, indent=2))
